CREATE INDEX FCB.ACTYPITM_ACPF_GHPI ON FCB.T_ACCOUNTTYPEITEM
(C_ACCOUNTID, "C_ISSUANCEID" DESC, C_BRANCHID)
  TABLESPACE FCB_UINX
GLOBAL PARTITION BY HASH (C_ACCOUNTID) (  
  PARTITIONs(4096)
)
PARALLEL ( DEGREE 8  );




CREATE INDEX FCB.ACTYPITM_ATYPF_GHPI ON FCB.T_ACCOUNTTYPEITEM
(C_ACCOUNTTYPEID, C_ISSUANCEID, C_BRANCHID)
  TABLESPACE FCB_UINX
GLOBAL PARTITION BY HASH (C_ACCOUNTTYPEID) 
partitions(4096)
PARALLEL ( DEGREE 8  );



CREATE UNIQUE INDEX FCB.PK_ACCOUNTTYPEITEM ON FCB.T_ACCOUNTTYPEITEM
(ID)
  TABLESPACE FCB_UTBL
  GLOBAL PARTITION BY HASH (ID) 
  partitions (4096)
PARALLEL ( DEGREE 8  )
REVERSE;





ALTER TABLE FCB.T_ACCOUNTTYPEITEM ADD (
  CONSTRAINT PK_ACCOUNTTYPEITEM
 PRIMARY KEY
 (ID) novalidate );
 
 
 
 