select * 
	from v$sgastat where pool= 'shared pool' and lower(name) like '%free%'


select 'exec DBMS_SHARED_POOL.KEEP(''' || owner || '.' || object_name || ''', ''Q'');' a
    FROM DBA_OBJECTS
    WHERE OWNER in ('FCB', 'ACHUSER')
      AND object_type = 'SEQUENCE'
      AND object_name in (select name from v$db_object_cache where kept <> 'YES' and type like '%SEQUENCE%' and owner in ('FCB', 'ACHUSER'))

begin
  --SEQUENCE
exec DBMS_SHARED_POOL.KEEP('ACHUSER.CTSEQUENCE', 'Q');
...
  --TRIGGER
  DBMS_SHARED_POOL.KEEP('FCB.TRG_DOCUMENT_M_CDATE1016N', 'R');
begin
end;
/



begin
  DBMS_SHARED_POOL.KEEP('FCB.UPDATE_DEPOSIT', 'R');
  DBMS_SHARED_POOL.KEEP('FCB.TRG_MONITODEPINTEREST_CHANGE', 'R');
  DBMS_SHARED_POOL.KEEP('FCB.TRG_ACCOUNT_INFO', 'R');
  DBMS_SHARED_POOL.KEEP('FCB.INSERT_YARANE_LETTER', 'R');
  DBMS_SHARED_POOL.KEEP('FCB.INSERT_SMS_ATTRIBUTES', 'R');
  DBMS_SHARED_POOL.KEEP('FCB.INSERT_RECOVERABLEDRAFT', 'R');
  DBMS_SHARED_POOL.KEEP('FCB.INSERT_CUSTOMERLOG_OPERATION_P', 'R');
  DBMS_SHARED_POOL.KEEP('FCB.DB_LOGON', 'R');  
  DBMS_SHARED_POOL.KEEP('FCB.PKG_FCB_CONTEXT', 'P');
  DBMS_SHARED_POOL.KEEP('OVEISI.OVEISI_LOG', 'R');
  DBMS_SHARED_POOL.KEEP('DBADMIN.TRG_PREVENT_DROPTRUNCATE', 'R');
  dbms_shared_pool.keep ('SYS.DBMS_APPLICATION_INFO', 'P');
  DBMS_SHARED_POOL.KEEP('FCB.TRG_DOCMENT_ADD_DOC_COMMENT', 'R');
  DBMS_SHARED_POOL.KEEP('FCB.TRG_DOCMENTITEM_INSERT', 'R');
end;



exec  DBMS_SHARED_POOL.KEEP('FCB.UPDATE_DEPOSIT', 'R');
exec  DBMS_SHARED_POOL.KEEP('FCB.TRG_MONITODEPINTEREST_CHANGE', 'R');
exec  DBMS_SHARED_POOL.KEEP('FCB.TRG_ACCOUNT_INFO', 'R');
exec  DBMS_SHARED_POOL.KEEP('FCB.INSERT_YARANE_LETTER', 'R');
exec  DBMS_SHARED_POOL.KEEP('FCB.INSERT_SMS_ATTRIBUTES', 'R');
exec  DBMS_SHARED_POOL.KEEP('FCB.INSERT_RECOVERABLEDRAFT', 'R');
exec  DBMS_SHARED_POOL.KEEP('FCB.INSERT_CUSTOMERLOG_OPERATION_P', 'R');
exec  DBMS_SHARED_POOL.KEEP('FCB.DB_LOGON', 'R');  
exec  DBMS_SHARED_POOL.KEEP('FCB.PKG_FCB_CONTEXT', 'P');
exec  DBMS_SHARED_POOL.KEEP('OVEISI.OVEISI_LOG', 'R');
exec  DBMS_SHARED_POOL.KEEP('DBADMIN.TRG_PREVENT_DROPTRUNCATE', 'R');
exec  dbms_shared_pool.keep ('SYS.DBMS_APPLICATION_INFO', 'P');
exec  DBMS_SHARED_POOL.KEEP('FCB.TRG_DOCMENT_ADD_DOC_COMMENT', 'R');
exec  DBMS_SHARED_POOL.KEEP('FCB.TRG_DOCMENTITEM_INSERT', 'R');




